name: whois
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-140.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  provider: ^5.0.0
  get_it: ^6.0.0
  intl: ^0.17.0
  shared_preferences: ^2.0.8
  url_strategy: ^0.2.0
  flutter_launcher_icons: "^0.9.2"
  fluttertoast: ^8.0.8
  rive: ^0.7.22
  url_launcher: ^6.0.12
  firebase_core: ^1.3.0
  firebase_messaging: ^10.0.2

dev_dependencies:
  
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets: 
   - assets/animation/anim.riv

  fonts:
      - family: OpenSans
        fonts:
          - asset: assets/fonts/OpenSans-Regular.ttf
          - asset: assets/fonts/OpenSans-Bold.ttf
            weight: 700
          - asset: assets/fonts/OpenSans-Italic.ttf
            style: italic

